name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    name: Tests on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.1
      - uses: Hanaasagi/zig-action-cache@master
        with:
          cache-on-failure: true
      - run: zig version
      - run: zig env
      - name: Build
        run: zig build
      - name: Run Tests
        run: zig build test
